<?xml version="1.0" encoding="utf-8"?>
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" ></meta>
        <meta http-equiv="Expires" content="0" />
        <title>scala/xml/include/XIncludeException.scala</title>
        <script type="text/javascript" src="../../../jquery-all.js"></script>
        <script type="text/javascript" src="../../../linked.js"></script>
        <link rel="stylesheet" type="text/css" href="../../../style.css" title="Style"></link>
    </head>
    <body>
        <pre>
/*                     __                                               *\
**     ________ ___   / /  ___     Scala API                            **
**    / __/ __// _ | / /  / _ |    (c) 2002-2013, LAMP/EPFL             **
**  __\ \/ /__/ __ |/ /__/ __ |    http://scala-lang.org/               **
** /____/\___/_/ |_/____/_/ | |                                         **
**                          |/                                          **
\*                                                                      */

<span class="keyword">package</span> scala.xml
<span class="keyword">package</span> include

/**
 * `XIncludeException` is the generic superclass for all checked exceptions
 * that may be thrown as a result of a violation of XInclude's rules.
 *
 * Constructs an `XIncludeException` with the specified detail message.
 * The error message string `message` can later be retrieved by the
 * `{@link java.lang.Throwable#getMessage}`
 * method of class `java.lang.Throwable`.
 *
 * @param   message   the detail message.
 */
<span class="keyword">class</span> <a title="class XIncludeException extends Exception" id="21504">XIncludeException</a><a href="#21504" title="scala.xml.include.XIncludeException" class="delimiter">(</a><a title="String" id="423277">message</a>: <span title="String">String</span><span class="delimiter">)</span> <span class="keyword">extends</span> <a href="../../package.scala.html#22170" title="Exception">Exception</a><span class="delimiter">(</span><a href="#423277" title="String">message</a><span class="delimiter">)</span> <span class="delimiter">{</span>

  /**
   * uses `'''null'''` as its error detail message.
   */
  <span class="keyword">def</span> <a title="()scala.xml.include.XIncludeException" id="423260" class="keyword">this</a><span class="delimiter">(</span><span class="delimiter">)</span> = <a href="#21504" title="XIncludeException.this.type" class="keyword">this</a><span class="delimiter">(</span><span title="Null(null)" class="keyword">null</span><span class="delimiter">)</span>

  <span class="keyword">private</span> <span class="keyword">var</span> <a title="Throwable" id="423262">rootCause</a>: <span title="Throwable">Throwable</span> = <span title="Null(null)" class="keyword">null</span>

  /**
   * When an `IOException`, `MalformedURLException` or other generic
   * exception is thrown while processing an XML document for XIncludes,
   * it is customarily replaced by some form of `XIncludeException`.
   * This method allows you to store the original exception.
   *
   * @param   nestedException   the underlying exception which
   * caused the XIncludeException to be thrown
   */
  <span class="keyword">def</span> <a title="(nestedException: Throwable)Unit" id="423264">setRootCause</a><span class="delimiter">(</span><a title="Throwable" id="423331">nestedException</a>: <span title="Throwable">Throwable</span> <span class="delimiter">)</span> <span class="delimiter">{</span>
    <a href="#21504" title="XIncludeException.this.type" class="keyword">this</a>.<a href="#423262" title="(x$1: Throwable)Unit">rootCause</a> = <a href="#423331" title="Throwable">nestedException</a>
  <span class="delimiter">}</span>

  /**
   * When an `IOException`, `MalformedURLException` or other generic
   * exception is thrown while processing an XML document for XIncludes,
   * it is customarily replaced by some form of `XIncludeException`.
   * This method allows you to retrieve the original exception.
   * It returns null if no such exception caused this `XIncludeException`.
   *
   * @return Throwable   the underlying exception which caused the
   *                     `XIncludeException` to be thrown
   */
  <span class="keyword">def</span> <a title="()Throwable" id="423265">getRootCause</a><span class="delimiter">(</span><span class="delimiter">)</span>: <span title="Throwable">Throwable</span> = <a href="#21504" title="XIncludeException.this.type" class="keyword">this</a>.<a href="#423262" title="=&gt; Throwable">rootCause</a>

<span class="delimiter">}</span>

        </pre>
    </body>
</html>